//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HUIAdminContainer : DbContext
    {
        public HUIAdminContainer()
            : base("name=HUIAdminContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> AdminSet { get; set; }
        public DbSet<Role> RoleSet { get; set; }
        public DbSet<Action> ActionSet { get; set; }
        public DbSet<Admin_Role> Admin_RoleSet { get; set; }
        public DbSet<Role_Action> Role_ActionSet { get; set; }
        public DbSet<Admin_Action> Admin_ActionSet { get; set; }
    }
}
